version: '3.7'
networks:
    traefik-public:
        external: false
    internal:
        external: false
services: 
    airflow:
        labels:
            - "traefik.http.routers.airflow.rule=Host(`airflow.${DOMAIN}`)"
            - "traefik.http.services.airflow.loadbalancer.server.port=8080"
    flower:
        labels:
            - "traefik.http.routers.flower.rule=Host(`flower.${DOMAIN}`)"
            - "traefik.http.services.flower.loadbalancer.server.port=5555"
    minio:
        labels:
            - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN}`)"
    mlflow:
        labels:
            - "traefik.http.routers.mlflow.rule=Host(`mlflow.${DOMAIN}`)"
            - "traefik.http.services.mlflow.loadbalancer.server.port=5000"
    pgadmin:
        labels:
            - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN}`)"
    proxy:
        command: 
            - --providers.docker
        networks:
            internal:
                aliases: 
                    - minio.localhost
            traefik-public:
        ports:
            - 80:80