FROM python:3.7-slim-buster

WORKDIR /src/

RUN apt update && \
    apt-get install -y \
    gcc

RUN pip install "apache-airflow[celery,crypto,postgres]" poetry tenacity && \
    poetry config virtualenvs.create false

COPY src/pyproject.toml src/poetry.lock*  /src/

# Add source code
COPY src/ /src/

# Add scripts
COPY ./airflow/scripts/ /scripts

RUN poetry install